import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import arsalan from "../public/arsalan.jpg";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import HoverCard from "@darenft/react-3d-hover-card";
import {useTypewriter, Cursor} from 'react-simple-typewriter'

import "@darenft/react-3d-hover-card/dist/style.css";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
    const [text] = useTypewriter({
    words: [
      "With expertise in both front-end and back-end technologies, I excel in designing and implementing seamless, scalable solutions. My technical skills are complemented by a strong commitment to continuous learning and staying current with the latest industry trends.",
    ],
    loop: 0, // Set to 0 to disable looping
    typeSpeed: 20, // Speed at which to type the text
    deleteSpeed: 50, // Speed at which to delete the text
    delaySpeed: 1000, // Delay before starting to type again
  });

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Arsalan Fahim</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">Arsalan Fahim</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  Contact
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Arsalan Fahim 
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              FullStack Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              {text}
              <Cursor />
            </p>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={arsalan} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">About Me</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I am a skilled fullstack developer with expertise in creating dynamic web applications. I am also dedicated to continuous learning and staying updated with industry trends, ensuring top-quality results in every project
            </p>
          </div>
          <div className="lg:flex gap-10">
            <HoverCard scaleFactor={1.2}>
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Designer
              </h3>
              <p className="py-2">
                Creating elegant designs following core
                design theory.
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Figma</p>
            </div>
            </HoverCard>
            <HoverCard scaleFactor={1.2}>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Coder
              </h3>
              <p className="py-2">
                Coded for 3 years, familiar with trending languages and frameworks
              </p>
              <h4 className="py-4 text-teal-600">Languages I Use</h4>
              <p className="text-gray-800 py-1">JavaScript</p>
              <p className="text-gray-800 py-1">Java</p>
              <p className="text-gray-800 py-1">Python</p>
              <p className="text-gray-800 py-1">Ruby</p>
            </div>
            </HoverCard>
            <HoverCard scaleFactor={1.2}>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={consulting} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Consultant</h3>
              <p className="py-2">
                Previous consultant for large companys
              </p>
              <h4 className="py-4 text-teal-600">Previous Clients</h4>
              <p className="text-gray-800 py-1">Coca Cola</p>
              <p className="text-gray-800 py-1">Pepsi</p>
              <p className="text-gray-800 py-1">Nike</p>
            </div>
            </HoverCard>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Contact Me</h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              I am always open to discussing new projects, creative ideas, or opportunities to be part of your vision. Feel free to reach out through any of the following channels:
            </p>
            <ul>
              <li><strong>Email:</strong> <a href="mailto:your.email@example.com" className="text-blue-500 hover:underline">arsalan_fahim@gmail.com</a></li>
              <li><strong>LinkedIn:</strong> <a href="https://linkedin.com/in/yourprofile" className="text-blue-500 hover:underline">linkedin.com/in/arsalan-fahim-03</a></li>
              <li><strong>GitHub:</strong> <a href="https://github.com/yourusername" className="text-blue-500 hover:underline">github.com/arsalanfahim</a></li>
            </ul>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              Looking forward to connecting with you!
            </p>
          </div>
        </section>
      </main>
    </div>
  );
}
